--IDE
 INSERT into COMT_IDS(TABLE_NAME,NEXT_ID) values ('BBS_ID',1);
 INSERT into COMT_IDS(TABLE_NAME,NEXT_ID) values ('FILE_ID',10001);
 INSERT into COMT_IDS(TABLE_NAME,NEXT_ID) values ('ATCH_FILE_ID',101);
 INSERT into COMT_IDS(TABLE_NAME,NEXT_ID) values ('BBS_NTT_ID',10001);
 INSERT into COMT_IDS(TABLE_NAME,NEXT_ID) values ('GROUP_ID',10001);
 INSERT into COMT_IDS(TABLE_NAME,NEXT_ID) values ('LOGINLOG_ID',10001);
 INSERT into COMT_IDS(TABLE_NAME,NEXT_ID) values ('ROLE_ID',10001);
 INSERT into COMT_IDS(TABLE_NAME,NEXT_ID) values ('SYSLOG_ID',10001);
 INSERT into COMT_IDS(TABLE_NAME,NEXT_ID) values ('DETAIL_CD',10001);



