DROP TABLE LETTNLOGINLOG CASCADE CONSTRAINTS;
CREATE TABLE LETTNLOGINLOG (
  LOG_ID char(20) NOT NULL,
  CONECT_ID varchar2(20) ,
  CONECT_IP varchar2(23) ,
  CONECT_MTHD char(4) ,
  ERROR_OCCRRNC_AT char(1) ,
  ERROR_CODE char(3) ,
  CREAT_DT DATE ,
  CONSTRAINT LETTNLOGINLOG_PK PRIMARY KEY (LOG_ID)
) ;

DROP TABLE LETTSSYSLOGSUMMARY CASCADE CONSTRAINTS;
CREATE TABLE LETTSSYSLOGSUMMARY (
  OCCRRNC_DE char(20) NOT NULL,
  SRVC_NM varchar2(255) NOT NULL,
  METHOD_NM varchar2(60) NOT NULL,
  CREAT_CO number(10,0) ,
  UPDT_CO number(10,0) ,
  RDCNT number(10,0) ,
  DELETE_CO number(10,0) ,
  OUTPT_CO number(10,0) ,
  ERROR_CO number(10,0) ,
  CONSTRAINT LETTSSYSLOGSUMMARY_PK PRIMARY KEY (OCCRRNC_DE,SRVC_NM,METHOD_NM)
) ;