
CREATE TABLE COMT_AUTHOR_GROUP
(
	GROUP_CD             VARCHAR(15) NOT NULL,
	AUTHOR_CD            VARCHAR(15) NOT NULL
);



ALTER TABLE COMT_AUTHOR_GROUP
ADD PRIMARY KEY (GROUP_CD,AUTHOR_CD);



CREATE TABLE COMT_BBS_ANSWER
(
	ANSWER_ID            VARCHAR(20) NOT NULL,
	ANSWER_CN            VARCHAR(4000) NULL,
	REGIST_DT            DATETIME NULL,
	REGISTER_ID          VARCHAR(20) NULL,
	UPDUSR_ID            VARCHAR(20) NULL,
	UPDT_DT              DATETIME NULL,
	NTT_ID               VARCHAR(20) NOT NULL
);



ALTER TABLE COMT_BBS_ANSWER
ADD PRIMARY KEY (ANSWER_ID);



-- 테이블 라벨 MySQL
ALTER TABLE COMT_BBS_ANSWER COMMENT = '게시판 댓글';


-- 테이블 라벨 끝

-- 컬럼 라벨 MySQL
ALTER TABLE COMT_BBS_ANSWER 
  CHANGE COLUMN ANSWER_ID 
  ANSWER_ID VARCHAR(20) NOT NULL 
  
  COMMENT '댓글 아이디 ';
 ALTER TABLE COMT_BBS_ANSWER 
  CHANGE COLUMN NTT_ID 
  NTT_ID VARCHAR(20) NOT NULL 
  
  COMMENT '게시물 아이디 ';
 ALTER TABLE COMT_BBS_ANSWER 
  CHANGE COLUMN ANSWER_CN 
  ANSWER_CN VARCHAR(4000) NULL 
  
  COMMENT '댓글 내용 ';
 ALTER TABLE COMT_BBS_ANSWER 
  CHANGE COLUMN REGISTER_ID 
  REGISTER_ID VARCHAR(20) NULL 
  
  COMMENT '등록자 아이디 ';
 ALTER TABLE COMT_BBS_ANSWER 
  CHANGE COLUMN REGIST_DT 
  REGIST_DT DATETIME NULL 
  
  COMMENT '등록 일시 ';
 ALTER TABLE COMT_BBS_ANSWER 
  CHANGE COLUMN UPDUSR_ID 
  UPDUSR_ID VARCHAR(20) NULL 
  
  COMMENT '수정자 아이디 ';
 ALTER TABLE COMT_BBS_ANSWER 
  CHANGE COLUMN UPDT_DT 
  UPDT_DT DATETIME NULL 
  
  COMMENT '수정 일시 ';
 



-- 컬럼 라벨 끝



CREATE TABLE COMT_BBS_MASTER
(
	BBS_NM               VARCHAR(255) NULL,
	BBS_ID               VARCHAR(20) NOT NULL,
	BBS_DC               VARCHAR(2400) NULL,
	ANSWER_USE_AT        CHAR(1) NULL,
	BBS_TY_CD            VARCHAR(15) NULL,
	REPLY_USE_AT         CHAR(1) NULL,
	FILE_ATCH_POSBL_NUMBER INTEGER NULL,
	FILE_ATCH_POSBL_SIZE INTEGER NULL,
	REGIST_DT            DATETIME NULL,
	REGISTER_ID          VARCHAR(20) NULL,
	UPDUSR_ID            VARCHAR(20) NULL,
	UPDT_DT              DATETIME NULL
);



ALTER TABLE COMT_BBS_MASTER
ADD PRIMARY KEY (BBS_ID);



-- 테이블 라벨 MySQL
ALTER TABLE COMT_BBS_MASTER COMMENT = '게시판 마스터';


-- 테이블 라벨 끝

-- 컬럼 라벨 MySQL
ALTER TABLE COMT_BBS_MASTER 
  CHANGE COLUMN BBS_ID 
  BBS_ID VARCHAR(20) NOT NULL 
  
  COMMENT '게시판 아이디 ';
 ALTER TABLE COMT_BBS_MASTER 
  CHANGE COLUMN BBS_NM 
  BBS_NM VARCHAR(255) NULL 
  
  COMMENT '게시판 명 ';
 ALTER TABLE COMT_BBS_MASTER 
  CHANGE COLUMN BBS_DC 
  BBS_DC VARCHAR(2400) NULL 
  
  COMMENT '게시판 설명 ';
 ALTER TABLE COMT_BBS_MASTER 
  CHANGE COLUMN BBS_TY_CD 
  BBS_TY_CD VARCHAR(15) NULL 
  
  COMMENT '게시판 유형 코드 ';
 ALTER TABLE COMT_BBS_MASTER 
  CHANGE COLUMN REPLY_USE_AT 
  REPLY_USE_AT CHAR(1) NULL 
  
  COMMENT '답장 사용 여부 ';
 ALTER TABLE COMT_BBS_MASTER 
  CHANGE COLUMN FILE_ATCH_POSBL_NUMBER 
  FILE_ATCH_POSBL_NUMBER INTEGER NULL 
  
  COMMENT '파일 첨부 가능 숫자 ';
 ALTER TABLE COMT_BBS_MASTER 
  CHANGE COLUMN FILE_ATCH_POSBL_SIZE 
  FILE_ATCH_POSBL_SIZE INTEGER NULL 
  
  COMMENT '파일 첨부 가능 사이즈 ';
 ALTER TABLE COMT_BBS_MASTER 
  CHANGE COLUMN ANSWER_USE_AT 
  ANSWER_USE_AT CHAR(1) NULL 
  
  COMMENT '댓글 사용 여부 ';
 ALTER TABLE COMT_BBS_MASTER 
  CHANGE COLUMN REGISTER_ID 
  REGISTER_ID VARCHAR(20) NULL 
  
  COMMENT '등록자 아이디 ';
 ALTER TABLE COMT_BBS_MASTER 
  CHANGE COLUMN REGIST_DT 
  REGIST_DT DATETIME NULL 
  
  COMMENT '등록 일시 ';
 ALTER TABLE COMT_BBS_MASTER 
  CHANGE COLUMN UPDUSR_ID 
  UPDUSR_ID VARCHAR(20) NULL 
  
  COMMENT '수정자 아이디 ';
 ALTER TABLE COMT_BBS_MASTER 
  CHANGE COLUMN UPDT_DT 
  UPDT_DT DATETIME NULL 
  
  COMMENT '수정 일시 ';
 



-- 컬럼 라벨 끝



CREATE TABLE COMT_BBS_NTT
(
	BBS_ID               VARCHAR(20) NOT NULL,
	PARNTS_NTT_ID        NUMERIC NULL,
	ANSWER_ORDR          INTEGER NULL,
	ANSWER_LEVEL         INTEGER NULL,
	NTT_SJ               VARCHAR(2000) NULL,
	NTT_CN               LONGTEXT NULL,
	RDCNT                INTEGER NULL,
	USE_AT               CHAR(1) NULL,
	REGIST_DT            DATETIME NULL,
	REGISTER_ID          VARCHAR(20) NULL,
	UPDT_DT              DATETIME NULL,
	UPDUSR_ID            VARCHAR(20) NULL,
	ATCH_FILE_ID         VARCHAR(20) NULL,
	NTT_ID               VARCHAR(20) NOT NULL
);



ALTER TABLE COMT_BBS_NTT
ADD PRIMARY KEY (NTT_ID);



-- 테이블 라벨 MySQL
ALTER TABLE COMT_BBS_NTT COMMENT = '게시판 게시물';


-- 테이블 라벨 끝

-- 컬럼 라벨 MySQL
ALTER TABLE COMT_BBS_NTT 
  CHANGE COLUMN NTT_ID 
  NTT_ID VARCHAR(20) NOT NULL 
  
  COMMENT '게시물 아이디 ';
 ALTER TABLE COMT_BBS_NTT 
  CHANGE COLUMN BBS_ID 
  BBS_ID VARCHAR(20) NOT NULL 
  
  COMMENT '게시판 아이디 ';
 ALTER TABLE COMT_BBS_NTT 
  CHANGE COLUMN NTT_SJ 
  NTT_SJ VARCHAR(2000) NULL 
  
  COMMENT '게시물 제목 ';
 ALTER TABLE COMT_BBS_NTT 
  CHANGE COLUMN NTT_CN 
  NTT_CN LONGTEXT NULL 
  
  COMMENT '게시물 내용 ';
 ALTER TABLE COMT_BBS_NTT 
  CHANGE COLUMN PARNTS_NTT_ID 
  PARNTS_NTT_ID NUMERIC NULL 
  
  COMMENT '부모 게시물 아이디 ';
 ALTER TABLE COMT_BBS_NTT 
  CHANGE COLUMN ANSWER_ORDR 
  ANSWER_ORDR INTEGER NULL 
  
  COMMENT '답글 순서 ';
 ALTER TABLE COMT_BBS_NTT 
  CHANGE COLUMN ANSWER_LEVEL 
  ANSWER_LEVEL INTEGER NULL 
  
  COMMENT '답글 레벨 ';
 ALTER TABLE COMT_BBS_NTT 
  CHANGE COLUMN RDCNT 
  RDCNT INTEGER NULL 
  
  COMMENT '조회수 ';
 ALTER TABLE COMT_BBS_NTT 
  CHANGE COLUMN USE_AT 
  USE_AT CHAR(1) NULL 
  
  COMMENT '사용 여부 ';
 ALTER TABLE COMT_BBS_NTT 
  CHANGE COLUMN ATCH_FILE_ID 
  ATCH_FILE_ID VARCHAR(20) NULL 
  
  COMMENT '첨부 파일 아이디 ';
 ALTER TABLE COMT_BBS_NTT 
  CHANGE COLUMN REGISTER_ID 
  REGISTER_ID VARCHAR(20) NULL 
  
  COMMENT '등록자 아이디 ';
 ALTER TABLE COMT_BBS_NTT 
  CHANGE COLUMN REGIST_DT 
  REGIST_DT DATETIME NULL 
  
  COMMENT '등록 일시 ';
 ALTER TABLE COMT_BBS_NTT 
  CHANGE COLUMN UPDUSR_ID 
  UPDUSR_ID VARCHAR(20) NULL 
  
  COMMENT '수정자 아이디 ';
 ALTER TABLE COMT_BBS_NTT 
  CHANGE COLUMN UPDT_DT 
  UPDT_DT DATETIME NULL 
  
  COMMENT '수정 일시 ';
 



-- 컬럼 라벨 끝



CREATE TABLE COMT_CL_CD
(
	CL_CD                CHAR(3) NOT NULL,
	CL_CD_NM             VARCHAR(60) NULL,
	REGIST_DT            DATETIME NULL,
	REGISTER_ID          VARCHAR(20) NULL,
	UPDT_DT              DATETIME NULL,
	UPDUSR_ID            VARCHAR(20) NULL,
	CL_CD_DC             VARCHAR(200) NULL
);



ALTER TABLE COMT_CL_CD
ADD PRIMARY KEY (CL_CD);



-- 테이블 라벨 MySQL
ALTER TABLE COMT_CL_CD COMMENT = '분류 코드';


-- 테이블 라벨 끝

-- 컬럼 라벨 MySQL
ALTER TABLE COMT_CL_CD 
  CHANGE COLUMN CL_CD 
  CL_CD CHAR(3) NOT NULL 
  
  COMMENT '분류 코드 ';
 ALTER TABLE COMT_CL_CD 
  CHANGE COLUMN CL_CD_NM 
  CL_CD_NM VARCHAR(60) NULL 
  
  COMMENT '분류 코드 명 ';
 ALTER TABLE COMT_CL_CD 
  CHANGE COLUMN CL_CD_DC 
  CL_CD_DC VARCHAR(200) NULL 
  
  COMMENT '분류 코드 설명 ';
 ALTER TABLE COMT_CL_CD 
  CHANGE COLUMN REGIST_DT 
  REGIST_DT DATETIME NULL 
  
  COMMENT '등록 일시 ';
 ALTER TABLE COMT_CL_CD 
  CHANGE COLUMN REGISTER_ID 
  REGISTER_ID VARCHAR(20) NULL 
  
  COMMENT '등록자 ID ';
 ALTER TABLE COMT_CL_CD 
  CHANGE COLUMN UPDT_DT 
  UPDT_DT DATETIME NULL 
  
  COMMENT '수정 일시 ';
 ALTER TABLE COMT_CL_CD 
  CHANGE COLUMN UPDUSR_ID 
  UPDUSR_ID VARCHAR(20) NULL 
  
  COMMENT '수정자 ID ';
 



-- 컬럼 라벨 끝



CREATE TABLE COMT_CMMN_CD
(
	CL_CD                CHAR(3) NOT NULL,
	CD_ID                VARCHAR(6) NOT NULL,
	CD_ID_NM             VARCHAR(60) NULL,
	CD_ID_DC             VARCHAR(200) NULL,
	REGIST_DT            DATETIME NULL,
	REGISTER_ID          VARCHAR(20) NULL,
	UPDT_DT              DATETIME NULL,
	UPDUSR_ID            VARCHAR(20) NULL
);



ALTER TABLE COMT_CMMN_CD
ADD PRIMARY KEY (CD_ID);



-- 테이블 라벨 MySQL
ALTER TABLE COMT_CMMN_CD COMMENT = '공통 코드';


-- 테이블 라벨 끝

-- 컬럼 라벨 MySQL
ALTER TABLE COMT_CMMN_CD 
  CHANGE COLUMN CD_ID 
  CD_ID VARCHAR(6) NOT NULL 
  
  COMMENT '코드 아이디 ';
 ALTER TABLE COMT_CMMN_CD 
  CHANGE COLUMN CL_CD 
  CL_CD CHAR(3) NOT NULL 
  
  COMMENT '분류 코드 ';
 ALTER TABLE COMT_CMMN_CD 
  CHANGE COLUMN CD_ID_NM 
  CD_ID_NM VARCHAR(60) NULL 
  
  COMMENT '코드 ID 명 ';
 ALTER TABLE COMT_CMMN_CD 
  CHANGE COLUMN CD_ID_DC 
  CD_ID_DC VARCHAR(200) NULL 
  
  COMMENT '코드 ID 설명 ';
 ALTER TABLE COMT_CMMN_CD 
  CHANGE COLUMN REGIST_DT 
  REGIST_DT DATETIME NULL 
  
  COMMENT '등록 일시 ';
 ALTER TABLE COMT_CMMN_CD 
  CHANGE COLUMN REGISTER_ID 
  REGISTER_ID VARCHAR(20) NULL 
  
  COMMENT '등록자 ID ';
 ALTER TABLE COMT_CMMN_CD 
  CHANGE COLUMN UPDT_DT 
  UPDT_DT DATETIME NULL 
  
  COMMENT '수정 일시 ';
 ALTER TABLE COMT_CMMN_CD 
  CHANGE COLUMN UPDUSR_ID 
  UPDUSR_ID VARCHAR(20) NULL 
  
  COMMENT '수정자 ID ';
 



-- 컬럼 라벨 끝



CREATE TABLE COMT_DETAIL_CD
(
	DETAIL_CD            VARCHAR(15) NULL,
	DETAIL_CD_NM         VARCHAR(60) NULL,
	DETAIL_CD_DC         VARCHAR(200) NULL,
	USE_AT               CHAR(1) NULL,
	REGIST_DT            DATETIME NULL,
	REGISTER_ID          VARCHAR(20) NULL,
	UPDT_DT              DATETIME NULL,
	UPDUSR_ID            VARCHAR(20) NULL,
	CD_ID                VARCHAR(6) NOT NULL,
	DETAIL_CD_ENG_NM     VARCHAR(60) NULL,
	DETAIL_CD_ORDR       INTEGER NULL,
	UPPER_CD             VARCHAR(15) NULL,
	DETAIL_CD_ID         VARCHAR(20) NOT NULL
);



ALTER TABLE COMT_DETAIL_CD
ADD PRIMARY KEY (DETAIL_CD_ID);



-- 테이블 라벨 MySQL
ALTER TABLE COMT_DETAIL_CD COMMENT = '상세 코드';


-- 테이블 라벨 끝

-- 컬럼 라벨 MySQL
ALTER TABLE COMT_DETAIL_CD 
  CHANGE COLUMN DETAIL_CD_ID 
  DETAIL_CD_ID VARCHAR(20) NOT NULL 
  
  COMMENT '상세 코드 아이디 ';
 ALTER TABLE COMT_DETAIL_CD 
  CHANGE COLUMN DETAIL_CD 
  DETAIL_CD VARCHAR(15) NULL 
  
  COMMENT '상세 코드 ';
 ALTER TABLE COMT_DETAIL_CD 
  CHANGE COLUMN CD_ID 
  CD_ID VARCHAR(6) NOT NULL 
  
  COMMENT '코드 아이디 ';
 ALTER TABLE COMT_DETAIL_CD 
  CHANGE COLUMN UPPER_CD 
  UPPER_CD VARCHAR(15) NULL 
  
  COMMENT '상위 코드 ';
 ALTER TABLE COMT_DETAIL_CD 
  CHANGE COLUMN DETAIL_CD_NM 
  DETAIL_CD_NM VARCHAR(60) NULL 
  
  COMMENT '상세 코드 명 ';
 ALTER TABLE COMT_DETAIL_CD 
  CHANGE COLUMN DETAIL_CD_ENG_NM 
  DETAIL_CD_ENG_NM VARCHAR(60) NULL 
  
  COMMENT '상세 코드 영문 명 ';
 ALTER TABLE COMT_DETAIL_CD 
  CHANGE COLUMN DETAIL_CD_DC 
  DETAIL_CD_DC VARCHAR(200) NULL 
  
  COMMENT '상세 코드 설명 ';
 ALTER TABLE COMT_DETAIL_CD 
  CHANGE COLUMN DETAIL_CD_ORDR 
  DETAIL_CD_ORDR INTEGER NULL 
  
  COMMENT '상세 코드 순서 ';
 ALTER TABLE COMT_DETAIL_CD 
  CHANGE COLUMN USE_AT 
  USE_AT CHAR(1) NULL 
  
  COMMENT '사용 여부 ';
 ALTER TABLE COMT_DETAIL_CD 
  CHANGE COLUMN REGIST_DT 
  REGIST_DT DATETIME NULL 
  
  COMMENT '등록 일시 ';
 ALTER TABLE COMT_DETAIL_CD 
  CHANGE COLUMN REGISTER_ID 
  REGISTER_ID VARCHAR(20) NULL 
  
  COMMENT '등록자 ID ';
 ALTER TABLE COMT_DETAIL_CD 
  CHANGE COLUMN UPDT_DT 
  UPDT_DT DATETIME NULL 
  
  COMMENT '수정 일시 ';
 ALTER TABLE COMT_DETAIL_CD 
  CHANGE COLUMN UPDUSR_ID 
  UPDUSR_ID VARCHAR(20) NULL 
  
  COMMENT '수정자 ID ';
 



-- 컬럼 라벨 끝



CREATE TABLE COMT_FILE_DETAIL
(
	FILE_ID              INTEGER NOT NULL,
	FILE_STRE_PATH       VARCHAR(2000) NULL,
	FILE_STRE_NM         VARCHAR(255) NULL,
	FILE_ORIGNL_NM       VARCHAR(255) NULL,
	FILE_EXTSN           VARCHAR(20) NULL,
	FILE_MG              INTEGER NULL,
	FILE_MASTER_ID       VARCHAR(20) NOT NULL,
	REGIST_DT            DATETIME NULL,
	REGISTER_ID          VARCHAR(20) NULL
);



ALTER TABLE COMT_FILE_DETAIL
ADD PRIMARY KEY (FILE_ID,FILE_MASTER_ID);



-- 테이블 라벨 MySQL
ALTER TABLE COMT_FILE_DETAIL COMMENT = '파일 상세';


-- 테이블 라벨 끝

-- 컬럼 라벨 MySQL
ALTER TABLE COMT_FILE_DETAIL 
  CHANGE COLUMN FILE_MASTER_ID 
  FILE_MASTER_ID VARCHAR(20) NOT NULL 
  
  COMMENT '파일 마스터 아이디 ';
 ALTER TABLE COMT_FILE_DETAIL 
  CHANGE COLUMN FILE_ID 
  FILE_ID INTEGER NOT NULL 
  
  COMMENT '파일 아이디 ';
 ALTER TABLE COMT_FILE_DETAIL 
  CHANGE COLUMN FILE_STRE_PATH 
  FILE_STRE_PATH VARCHAR(2000) NULL 
  
  COMMENT '파일 저장 경로 ';
 ALTER TABLE COMT_FILE_DETAIL 
  CHANGE COLUMN FILE_STRE_NM 
  FILE_STRE_NM VARCHAR(255) NULL 
  
  COMMENT '파일 저장 명 ';
 ALTER TABLE COMT_FILE_DETAIL 
  CHANGE COLUMN FILE_ORIGNL_NM 
  FILE_ORIGNL_NM VARCHAR(255) NULL 
  
  COMMENT '파일 원 명 ';
 ALTER TABLE COMT_FILE_DETAIL 
  CHANGE COLUMN FILE_EXTSN 
  FILE_EXTSN VARCHAR(20) NULL 
  
  COMMENT '파일 확장자 ';
 ALTER TABLE COMT_FILE_DETAIL 
  CHANGE COLUMN FILE_MG 
  FILE_MG INTEGER NULL 
  
  COMMENT '파일 크기 ';
 ALTER TABLE COMT_FILE_DETAIL 
  CHANGE COLUMN REGIST_DT 
  REGIST_DT DATETIME NULL 
  
  COMMENT '등록 일시 ';
 ALTER TABLE COMT_FILE_DETAIL 
  CHANGE COLUMN REGISTER_ID 
  REGISTER_ID VARCHAR(20) NULL 
  
  COMMENT '등록자 ID ';
 



-- 컬럼 라벨 끝



CREATE TABLE COMT_FILE_MASTER
(
	FILE_MASTER_ID       VARCHAR(20) NOT NULL,
	REGIST_DT            DATETIME NULL,
	USE_AT               CHAR(1) NULL,
	REGISTER_ID          VARCHAR(20) NULL
);



ALTER TABLE COMT_FILE_MASTER
ADD PRIMARY KEY (FILE_MASTER_ID);



-- 테이블 라벨 MySQL
ALTER TABLE COMT_FILE_MASTER COMMENT = '파일 마스터';


-- 테이블 라벨 끝

-- 컬럼 라벨 MySQL
ALTER TABLE COMT_FILE_MASTER 
  CHANGE COLUMN FILE_MASTER_ID 
  FILE_MASTER_ID VARCHAR(20) NOT NULL 
  
  COMMENT '파일 마스터 아이디 ';
 ALTER TABLE COMT_FILE_MASTER 
  CHANGE COLUMN USE_AT 
  USE_AT CHAR(1) NULL 
  
  COMMENT '사용 여부 ';
 ALTER TABLE COMT_FILE_MASTER 
  CHANGE COLUMN REGIST_DT 
  REGIST_DT DATETIME NULL 
  
  COMMENT '등록 일시 ';
 ALTER TABLE COMT_FILE_MASTER 
  CHANGE COLUMN REGISTER_ID 
  REGISTER_ID VARCHAR(20) NULL 
  
  COMMENT '등록자 ID ';
 



-- 컬럼 라벨 끝



CREATE TABLE COMT_IDS
(
	TABLE_NAME           VARCHAR(50) NOT NULL,
	NEXT_ID              NUMERIC(30) NULL
);



ALTER TABLE COMT_IDS
ADD PRIMARY KEY (TABLE_NAME);



-- 테이블 라벨 MySQL
ALTER TABLE COMT_IDS COMMENT = 'IDS';


-- 테이블 라벨 끝

-- 컬럼 라벨 MySQL
ALTER TABLE COMT_IDS 
  CHANGE COLUMN TABLE_NAME 
  TABLE_NAME VARCHAR(50) NOT NULL 
  
  COMMENT '테이블 이름 ';
 ALTER TABLE COMT_IDS 
  CHANGE COLUMN NEXT_ID 
  NEXT_ID NUMERIC(30) NULL 
  
  COMMENT '다음 아이디 ';
 



-- 컬럼 라벨 끝



CREATE TABLE COMT_MENU_CREAT_DTLS
(
	MENU_ID              VARCHAR(6) NOT NULL,
	LAYOUT_CD            VARCHAR(15) NOT NULL,
	GROUP_CD             VARCHAR(15) NOT NULL
);



ALTER TABLE COMT_MENU_CREAT_DTLS
ADD PRIMARY KEY (MENU_ID,LAYOUT_CD,GROUP_CD);



-- 테이블 라벨 MySQL
ALTER TABLE COMT_MENU_CREAT_DTLS COMMENT = '메뉴 생성 내역';


-- 테이블 라벨 끝

-- 컬럼 라벨 MySQL
ALTER TABLE COMT_MENU_CREAT_DTLS 
  CHANGE COLUMN GROUP_CD 
  GROUP_CD VARCHAR(15) NOT NULL 
  
  COMMENT '그룹 코드 ';
 ALTER TABLE COMT_MENU_CREAT_DTLS 
  CHANGE COLUMN MENU_ID 
  MENU_ID VARCHAR(6) NOT NULL 
  
  COMMENT '메뉴 아이디 ';
 ALTER TABLE COMT_MENU_CREAT_DTLS 
  CHANGE COLUMN LAYOUT_CD 
  LAYOUT_CD VARCHAR(15) NOT NULL 
  
  COMMENT '레이아웃 코드 ';
 



-- 컬럼 라벨 끝



CREATE TABLE COMT_MENU_INFO
(
	MENU_ID              VARCHAR(6) NOT NULL,
	UPPER_MENU_ID        VARCHAR(6) NULL,
	MENU_NM              VARCHAR(60) NULL,
	MENU_ORDR            NUMERIC(5) NULL,
	MENU_DC              VARCHAR(250) NULL,
	PROGRM_FILE_ID       VARCHAR(20) NOT NULL,
	RELATE_IMAGE_PATH    VARCHAR(250) NULL,
	RELATE_IMAGE_DC      VARCHAR(1000) NULL,
	LAYOUT_CD            VARCHAR(15) NOT NULL
);



ALTER TABLE COMT_MENU_INFO
ADD PRIMARY KEY (MENU_ID,LAYOUT_CD);



-- 테이블 라벨 MySQL
ALTER TABLE COMT_MENU_INFO COMMENT = '메뉴 정보';


-- 테이블 라벨 끝

-- 컬럼 라벨 MySQL
ALTER TABLE COMT_MENU_INFO 
  CHANGE COLUMN MENU_ID 
  MENU_ID VARCHAR(6) NOT NULL 
  
  COMMENT '메뉴 아이디 ';
 ALTER TABLE COMT_MENU_INFO 
  CHANGE COLUMN LAYOUT_CD 
  LAYOUT_CD VARCHAR(15) NOT NULL 
  
  COMMENT '레이아웃 코드 ';
 ALTER TABLE COMT_MENU_INFO 
  CHANGE COLUMN MENU_NM 
  MENU_NM VARCHAR(60) NULL 
  
  COMMENT '메뉴 명 ';
 ALTER TABLE COMT_MENU_INFO 
  CHANGE COLUMN UPPER_MENU_ID 
  UPPER_MENU_ID VARCHAR(6) NULL 
  
  COMMENT '상위 메뉴 아이디 ';
 ALTER TABLE COMT_MENU_INFO 
  CHANGE COLUMN MENU_ORDR 
  MENU_ORDR NUMERIC(5) NULL 
  
  COMMENT '메뉴 순서 ';
 ALTER TABLE COMT_MENU_INFO 
  CHANGE COLUMN MENU_DC 
  MENU_DC VARCHAR(250) NULL 
  
  COMMENT '메뉴 설명 ';
 ALTER TABLE COMT_MENU_INFO 
  CHANGE COLUMN PROGRM_FILE_ID 
  PROGRM_FILE_ID VARCHAR(20) NOT NULL 
  
  COMMENT '프로그램 파일 아이디 ';
 ALTER TABLE COMT_MENU_INFO 
  CHANGE COLUMN RELATE_IMAGE_PATH 
  RELATE_IMAGE_PATH VARCHAR(250) NULL 
  
  COMMENT '관계 이미지 경로 ';
 ALTER TABLE COMT_MENU_INFO 
  CHANGE COLUMN RELATE_IMAGE_DC 
  RELATE_IMAGE_DC VARCHAR(1000) NULL 
  
  COMMENT '관계 이미지 설명 ';
 



-- 컬럼 라벨 끝



CREATE TABLE COMT_POPUP_AREA
(
	LINK_TRGT            VARCHAR(20) NULL,
	INDICT_PD_BEGIN      DATE NULL,
	INDICT_PD_END        DATE NULL,
	REGIST_DT            DATE NULL,
	SN                   VARCHAR(20) NOT NULL,
	IDNTFC_WORDS         VARCHAR(100) NULL,
	LINK_URL             VARCHAR(200) NULL,
	MBER_SN              INTEGER NULL,
	REPLC_TEXT           VARCHAR(100) NULL
);



ALTER TABLE COMT_POPUP_AREA
ADD PRIMARY KEY (SN);



-- 테이블 라벨 MySQL
ALTER TABLE COMT_POPUP_AREA COMMENT = '팝업 지역';


-- 테이블 라벨 끝

-- 컬럼 라벨 MySQL
ALTER TABLE COMT_POPUP_AREA 
  CHANGE COLUMN SN 
  SN VARCHAR(20) NOT NULL 
  
  COMMENT '일련번호 ';
 ALTER TABLE COMT_POPUP_AREA 
  CHANGE COLUMN LINK_TRGT 
  LINK_TRGT VARCHAR(20) NULL 
  
  COMMENT '링크 타겟 ';
 ALTER TABLE COMT_POPUP_AREA 
  CHANGE COLUMN INDICT_PD_BEGIN 
  INDICT_PD_BEGIN DATE NULL 
  
  COMMENT '표시 기간 시작 ';
 ALTER TABLE COMT_POPUP_AREA 
  CHANGE COLUMN INDICT_PD_END 
  INDICT_PD_END DATE NULL 
  
  COMMENT '표시 기간 종료 ';
 ALTER TABLE COMT_POPUP_AREA 
  CHANGE COLUMN REGIST_DT 
  REGIST_DT DATE NULL 
  
  COMMENT '등록 일시 ';
 ALTER TABLE COMT_POPUP_AREA 
  CHANGE COLUMN IDNTFC_WORDS 
  IDNTFC_WORDS VARCHAR(100) NULL 
  
  COMMENT '식별 문구 ';
 ALTER TABLE COMT_POPUP_AREA 
  CHANGE COLUMN LINK_URL 
  LINK_URL VARCHAR(200) NULL 
  
  COMMENT '링크 URL ';
 ALTER TABLE COMT_POPUP_AREA 
  CHANGE COLUMN MBER_SN 
  MBER_SN INTEGER NULL 
  
  COMMENT '회원 일련번호 ';
 ALTER TABLE COMT_POPUP_AREA 
  CHANGE COLUMN REPLC_TEXT 
  REPLC_TEXT VARCHAR(100) NULL 
  
  COMMENT '대체 텍스트 ';
 



-- 컬럼 라벨 끝



CREATE TABLE COMT_POPUP_SETUP
(
	POPUP_CREAT_DE       DATE NULL,
	POPUP_BEGIN_DE       DATE NULL,
	POPUP_END_DE         DATE NULL,
	POPUP_ID             VARCHAR(20) NOT NULL,
	POPUP_SJ             VARCHAR(100) NULL,
	POPUP_USE_AT         CHAR(1) NULL,
	POPUP_LINK_ADRES     VARCHAR(200) NULL,
	POPUP_CN             TEXT NULL,
	POPUP_TRGT           VARCHAR(20) NULL,
	POPUP_LC_WIDTH       INTEGER NULL,
	POPUP_LC_VRTICL      INTEGER NULL,
	POPUP_MG_WIDTH       INTEGER NULL,
	POPUP_MG_VRTICL      INTEGER NULL
);



ALTER TABLE COMT_POPUP_SETUP
ADD PRIMARY KEY (POPUP_ID);



-- 테이블 라벨 MySQL
ALTER TABLE COMT_POPUP_SETUP COMMENT = '팝업 설정';


-- 테이블 라벨 끝

-- 컬럼 라벨 MySQL
ALTER TABLE COMT_POPUP_SETUP 
  CHANGE COLUMN POPUP_ID 
  POPUP_ID VARCHAR(20) NOT NULL 
  
  COMMENT '팝업 아이디 ';
 ALTER TABLE COMT_POPUP_SETUP 
  CHANGE COLUMN POPUP_CREAT_DE 
  POPUP_CREAT_DE DATE NULL 
  
  COMMENT '팝업 생성 일자 ';
 ALTER TABLE COMT_POPUP_SETUP 
  CHANGE COLUMN POPUP_BEGIN_DE 
  POPUP_BEGIN_DE DATE NULL 
  
  COMMENT '팝업 시작 일자 ';
 ALTER TABLE COMT_POPUP_SETUP 
  CHANGE COLUMN POPUP_END_DE 
  POPUP_END_DE DATE NULL 
  
  COMMENT '팝업 종료 일자 ';
 ALTER TABLE COMT_POPUP_SETUP 
  CHANGE COLUMN POPUP_SJ 
  POPUP_SJ VARCHAR(100) NULL 
  
  COMMENT '팝업 제목 ';
 ALTER TABLE COMT_POPUP_SETUP 
  CHANGE COLUMN POPUP_USE_AT 
  POPUP_USE_AT CHAR(1) NULL 
  
  COMMENT '팝업 사용 여부 ';
 ALTER TABLE COMT_POPUP_SETUP 
  CHANGE COLUMN POPUP_LINK_ADRES 
  POPUP_LINK_ADRES VARCHAR(200) NULL 
  
  COMMENT '팝업 링크 주소 ';
 ALTER TABLE COMT_POPUP_SETUP 
  CHANGE COLUMN POPUP_CN 
  POPUP_CN TEXT NULL 
  
  COMMENT '팝업 내용 ';
 ALTER TABLE COMT_POPUP_SETUP 
  CHANGE COLUMN POPUP_TRGT 
  POPUP_TRGT VARCHAR(20) NULL 
  
  COMMENT '팝업 타겟 ';
 ALTER TABLE COMT_POPUP_SETUP 
  CHANGE COLUMN POPUP_LC_WIDTH 
  POPUP_LC_WIDTH INTEGER NULL 
  
  COMMENT '팝업 위치 가로 ';
 ALTER TABLE COMT_POPUP_SETUP 
  CHANGE COLUMN POPUP_LC_VRTICL 
  POPUP_LC_VRTICL INTEGER NULL 
  
  COMMENT '팝업 위치 세로 ';
 ALTER TABLE COMT_POPUP_SETUP 
  CHANGE COLUMN POPUP_MG_WIDTH 
  POPUP_MG_WIDTH INTEGER NULL 
  
  COMMENT '팝업 크기 가로 ';
 ALTER TABLE COMT_POPUP_SETUP 
  CHANGE COLUMN POPUP_MG_VRTICL 
  POPUP_MG_VRTICL INTEGER NULL 
  
  COMMENT '팝업 크기 세로 ';
 



-- 컬럼 라벨 끝



CREATE TABLE COMT_PROGRM_MANAGE
(
	PROGRM_FILE_ID       VARCHAR(20) NOT NULL,
	PROGRM_STRE_PATH     VARCHAR(100) NULL,
	PROGRM_DC            VARCHAR(250) NULL,
	PROGRM_URL           VARCHAR(255) NULL,
	PROGRM_KOREAN_NM     VARCHAR(100) NULL
);



ALTER TABLE COMT_PROGRM_MANAGE
ADD PRIMARY KEY (PROGRM_FILE_ID);



-- 테이블 라벨 MySQL
ALTER TABLE COMT_PROGRM_MANAGE COMMENT = '프로그램 관리';


-- 테이블 라벨 끝

-- 컬럼 라벨 MySQL
ALTER TABLE COMT_PROGRM_MANAGE 
  CHANGE COLUMN PROGRM_FILE_ID 
  PROGRM_FILE_ID VARCHAR(20) NOT NULL 
  
  COMMENT '프로그램 파일 아이디 ';
 ALTER TABLE COMT_PROGRM_MANAGE 
  CHANGE COLUMN PROGRM_KOREAN_NM 
  PROGRM_KOREAN_NM VARCHAR(100) NULL 
  
  COMMENT '프로그램 한글 명 ';
 ALTER TABLE COMT_PROGRM_MANAGE 
  CHANGE COLUMN PROGRM_DC 
  PROGRM_DC VARCHAR(250) NULL 
  
  COMMENT '프로그램 설명 ';
 ALTER TABLE COMT_PROGRM_MANAGE 
  CHANGE COLUMN PROGRM_STRE_PATH 
  PROGRM_STRE_PATH VARCHAR(100) NULL 
  
  COMMENT '프로그램 저장 경로 ';
 ALTER TABLE COMT_PROGRM_MANAGE 
  CHANGE COLUMN PROGRM_URL 
  PROGRM_URL VARCHAR(255) NULL 
  
  COMMENT '프로그램 URL ';
 



-- 컬럼 라벨 끝



CREATE TABLE COMT_USER_INFO
(
	USER_NM              VARCHAR(50) NULL,
	USER_PASSWORD        VARCHAR(200) NULL,
	USER_ZIP             VARCHAR(6) NULL,
	USER_ADRES           VARCHAR(200) NULL,
	USER_DETAILADRES     VARCHAR(200) NULL,
	USER_MOBLPHON_NO     VARCHAR(20) NULL,
	USER_EMAIL           VARCHAR(50) NULL,
	REGIST_DT            DATETIME NULL,
	REGISTER_ID          VARCHAR(20) NULL,
	UPDUSR_ID            VARCHAR(20) NULL,
	UPDT_DT              DATETIME NULL,
	USER_ID              NUMERIC NOT NULL
);



ALTER TABLE COMT_USER_INFO
ADD PRIMARY KEY (USER_ID);



-- 테이블 라벨 MySQL
ALTER TABLE COMT_USER_INFO COMMENT = '유저 정보';


-- 테이블 라벨 끝

-- 컬럼 라벨 MySQL
ALTER TABLE COMT_USER_INFO 
  CHANGE COLUMN USER_ID 
  USER_ID NUMERIC NOT NULL 
  
  COMMENT '유저 아이디 ';
 ALTER TABLE COMT_USER_INFO 
  CHANGE COLUMN USER_NM 
  USER_NM VARCHAR(50) NULL 
  
  COMMENT '유저 명 ';
 ALTER TABLE COMT_USER_INFO 
  CHANGE COLUMN USER_PASSWORD 
  USER_PASSWORD VARCHAR(200) NULL 
  
  COMMENT '유저 비밀번호 ';
 ALTER TABLE COMT_USER_INFO 
  CHANGE COLUMN USER_ZIP 
  USER_ZIP VARCHAR(6) NULL 
  
  COMMENT '유저 우편번호 ';
 ALTER TABLE COMT_USER_INFO 
  CHANGE COLUMN USER_ADRES 
  USER_ADRES VARCHAR(200) NULL 
  
  COMMENT '유저 주소 ';
 ALTER TABLE COMT_USER_INFO 
  CHANGE COLUMN USER_DETAILADRES 
  USER_DETAILADRES VARCHAR(200) NULL 
  
  COMMENT '유저 상세주소 ';
 ALTER TABLE COMT_USER_INFO 
  CHANGE COLUMN USER_MOBLPHON_NO 
  USER_MOBLPHON_NO VARCHAR(20) NULL 
  
  COMMENT '유저 휴대전화 번호 ';
 ALTER TABLE COMT_USER_INFO 
  CHANGE COLUMN USER_EMAIL 
  USER_EMAIL VARCHAR(50) NULL 
  
  COMMENT '유저 이메일 ';
 ALTER TABLE COMT_USER_INFO 
  CHANGE COLUMN REGISTER_ID 
  REGISTER_ID VARCHAR(20) NULL 
  
  COMMENT '등록자 아이디 ';
 ALTER TABLE COMT_USER_INFO 
  CHANGE COLUMN REGIST_DT 
  REGIST_DT DATETIME NULL 
  
  COMMENT '등록 일시 ';
 ALTER TABLE COMT_USER_INFO 
  CHANGE COLUMN UPDUSR_ID 
  UPDUSR_ID VARCHAR(20) NULL 
  
  COMMENT '수정자 아이디 ';
 ALTER TABLE COMT_USER_INFO 
  CHANGE COLUMN UPDT_DT 
  UPDT_DT DATETIME NULL 
  
  COMMENT '수정 일시 ';
 



-- 컬럼 라벨 끝



CREATE TABLE COMT_ZIP
(
	SN                   VARCHAR(20) NOT NULL,
	ZIP                  VARCHAR(7) NULL,
	CTRD                 VARCHAR(4) NULL,
	GU_GUN               VARCHAR(13) NULL,
	DONG                 VARCHAR(44) NULL,
	LNBR                 VARCHAR(17) NULL
);



ALTER TABLE COMT_ZIP
ADD PRIMARY KEY (SN);



-- 테이블 라벨 MySQL
ALTER TABLE COMT_ZIP COMMENT = '우편번호';


-- 테이블 라벨 끝

-- 컬럼 라벨 MySQL
ALTER TABLE COMT_ZIP 
  CHANGE COLUMN SN 
  SN VARCHAR(20) NOT NULL 
  
  COMMENT '일련번호 ';
 ALTER TABLE COMT_ZIP 
  CHANGE COLUMN ZIP 
  ZIP VARCHAR(7) NULL 
  
  COMMENT '우편번호 ';
 ALTER TABLE COMT_ZIP 
  CHANGE COLUMN CTRD 
  CTRD VARCHAR(4) NULL 
  
  COMMENT '시도 ';
 ALTER TABLE COMT_ZIP 
  CHANGE COLUMN GU_GUN 
  GU_GUN VARCHAR(13) NULL 
  
  COMMENT '구군 ';
 ALTER TABLE COMT_ZIP 
  CHANGE COLUMN DONG 
  DONG VARCHAR(44) NULL 
  
  COMMENT '동 ';
 ALTER TABLE COMT_ZIP 
  CHANGE COLUMN LNBR 
  LNBR VARCHAR(17) NULL 
  
  COMMENT '번지 ';
 



-- 컬럼 라벨 끝



ALTER TABLE COMT_BBS_ANSWER
ADD FOREIGN KEY R_73 (NTT_ID) REFERENCES COMT_BBS_NTT (NTT_ID);



ALTER TABLE COMT_BBS_NTT
ADD FOREIGN KEY R_71 (BBS_ID) REFERENCES COMT_BBS_MASTER (BBS_ID);



ALTER TABLE COMT_CMMN_CD
ADD FOREIGN KEY R_175 (CL_CD) REFERENCES COMT_CL_CD (CL_CD);



ALTER TABLE COMT_DETAIL_CD
ADD FOREIGN KEY R_177 (CD_ID) REFERENCES COMT_CMMN_CD (CD_ID);



ALTER TABLE COMT_FILE_DETAIL
ADD FOREIGN KEY R_183 (FILE_MASTER_ID) REFERENCES COMT_FILE_MASTER (FILE_MASTER_ID);



ALTER TABLE COMT_MENU_CREAT_DTLS
ADD FOREIGN KEY R_182 (MENU_ID, LAYOUT_CD) REFERENCES COMT_MENU_INFO (MENU_ID, LAYOUT_CD);



ALTER TABLE COMT_MENU_INFO
ADD FOREIGN KEY R_179 (PROGRM_FILE_ID) REFERENCES COMT_PROGRM_MANAGE (PROGRM_FILE_ID);



ALTER TABLE COMT_MENU_INFO
ADD FOREIGN KEY R_181 (UPPER_MENU_ID, LAYOUT_CD) REFERENCES COMT_MENU_INFO (MENU_ID, LAYOUT_CD);





CREATE TABLE LETTNLOGINLOG (
  LOG_ID char(20) NOT NULL,
  CONECT_ID varchar(20) DEFAULT NULL,
  CONECT_IP varchar(23) DEFAULT NULL,
  CONECT_MTHD char(4) DEFAULT NULL,
  ERROR_OCCRRNC_AT char(1) DEFAULT NULL,
  ERROR_CODE char(3) DEFAULT NULL,
  CREAT_DT datetime DEFAULT NULL,
  PRIMARY KEY (LOG_ID)
) ;


CREATE TABLE LETTSSYSLOGSUMMARY (
  OCCRRNC_DE char(20) NOT NULL,
  SRVC_NM varchar(255) NOT NULL,
  METHOD_NM varchar(60) NOT NULL,
  CREAT_CO decimal(10,0) DEFAULT NULL,
  UPDT_CO decimal(10,0) DEFAULT NULL,
  RDCNT decimal(10,0) DEFAULT NULL,
  DELETE_CO decimal(10,0) DEFAULT NULL,
  OUTPT_CO decimal(10,0) DEFAULT NULL,
  ERROR_CO decimal(10,0) DEFAULT NULL,
  PRIMARY KEY (OCCRRNC_DE,SRVC_NM,METHOD_NM)
) ;